### ISSUE TITLE
[BUG] PDF_DELETION_TIME required

### ISSUE THREAD

**Issue by tryallthethings** [AmruthPillai/Reactive-Resume#1095]
**Describe the bug**

Not exactly a bug but an issue for new users nonetheless. I was just trying to spin up a docker instance via the docker-compose.yml file supplied in the repo. The UI was reachable, but I couldn't register an account (still can't currently). Upon checking the docker logs for the server, I noticed the following:
```
> reactive-resume@3.6.10 start /app
> env-cmd --silent turbo run start "--filter" "server"
 WARNING  cannot find a .git folder. Falling back to manual file hashing (which may be slower). If you are running this build in a pruned directory, you can ignore this message. Otherwise, please initialize a git repository in the root of your monorepo
• Packages in scope: @reactive-resume/server
• Running start in 1 packages
• Remote caching disabled
@reactive-resume/server:start: cache bypass, force executing ca8e1f6736c613de
@reactive-resume/server:start: 
@reactive-resume/server:start: > @reactive-resume/server@ start /app/server
@reactive-resume/server:start: > node dist/main
@reactive-resume/server:start: 
@reactive-resume/server:start: /app/node_modules/.pnpm/@nestjs+config@2.2.0_2kbkxfsrhtatemqz6dhv2pefvq/node_modules/@nestjs/config/dist/config.module.js:75
@reactive-resume/server:start:                 throw new Error(`Config validation error: ${error.message}`);
@reactive-resume/server:start:                 ^
@reactive-resume/server:start: 
@reactive-resume/server:start: Error: Config validation error: "PDF_DELETION_TIME" must be a number
@reactive-resume/server:start:     at Function.forRoot (/app/node_modules/.pnpm/@nestjs+config@2.2.0_2kbkxfsrhtatemqz6dhv2pefvq/node_modules/@nestjs/config/dist/config.module.js:75:23)
@reactive-resume/server:start:     at Object.<anonymous> (/app/server/dist/config/config.module.js:60:35)
@reactive-resume/server:start:     at Module._compile (node:internal/modules/cjs/loader:1155:14)
@reactive-resume/server:start:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
@reactive-resume/server:start:     at Module.load (node:internal/modules/cjs/loader:1033:32)
@reactive-resume/server:start:     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
@reactive-resume/server:start:     at Module.require (node:internal/modules/cjs/loader:1057:19)
@reactive-resume/server:start:     at require (node:internal/modules/cjs/helpers:103:18)
@reactive-resume/server:start:     at Object.<anonymous> (/app/server/dist/app.module.js:17:25)
@reactive-resume/server:start:     at Module._compile (node:internal/modules/cjs/loader:1155:14)
@reactive-resume/server:start:  ELIFECYCLE  Command failed with exit code 1.
@reactive-resume/server:start: ERROR: command finished with error: command (/app/server) pnpm run start exited (1)
command (/app/server) pnpm run start exited (1)
 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    2.885s 
 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
```

After assigning a value to PDF_DELETION_TIME (I used 30) the server seemed to start up.

**Product Flavor**

- [ ] Managed (https://rxresu.me)
- [X] Self Hosted

**To Reproduce**

1. Deploy docker container via docker-compose.yml in this GitHub repo without modifying the environment variables.
2. Check docker logs for server

**Expected behavior**

- PDF_DELETION_TIME should have a value assigned by default.
- Additionally, PDF_DELETION_TIME is not mentioned in the documentation at https://docs.rxresu.me/source-code/environment-variables. Is this value in seconds, hours, days?

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 107.0.5304.107

**Comment by AmruthPillai** [comment]
I see what must have happened. The PDF_DELETION_TIME env var is an optional field, but it also should be undefined. If it has been defined, there's a validation that it should be a number (hence the appropriate error).

I'll just make sure to allow empty strings as well so this error goes away, but also please ensure that the env variable does not exist in the list if you do not plan to use it.

Will push a fix for this in the upcoming release :)

**Comment by tryallthethings** [comment]
Thanks!

About the unused env variables: I followed the documentation over at https://docs.rxresu.me/deployment/docker but skipped using the .env file as the docker-compose.yml already had env variables in it. Loaded the docker-compose.yml as a stack in portainer and ran it. If those variables are optional, wouldn't it be better to comment them out for beginners like me?

And the second thing is that PDF_DELETION_TIME is missing in https://docs.rxresu.me/source-code/environment-variables

**Comment by AmruthPillai** [comment]
Good point, I've updated the docs to reflect the new env var too :) Thanks for helping to keep the project up to date!

**Comment by tryallthethings** [comment]
Cool! And you're welcome! 
Do you have any place besides GitHub issues for discussions? I'm still unable to use my instance. Or should I raise another issue?
