### ISSUE TITLE
Cannot Delete added items from Project section.

### ISSUE THREAD

**Issue by shivprasad94** [AmruthPillai/Reactive-Resume#1775]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

I have added 1 new item in Project items by Mistake
![image](https://github.com/AmruthPillai/Reactive-Resume/assets/13836633/00ca9eb8-bb72-4552-bbae-bdbf639dc0f7)

Now i have no option to delete it (No delete option here )
![image](https://github.com/AmruthPillai/Reactive-Resume/assets/13836633/89297364-4b86-495a-8eca-68becdf2a420)

If i remove all text and save it, i get below error
![image](https://github.com/AmruthPillai/Reactive-Resume/assets/13836633/b2aee1c2-f29d-4611-8e60-7c48ef6a56b3)

### Expected Behavior

There should be a delete button as well, or at least in the main Section, during reorder, we should have an option to delete 

### Steps To Reproduce

1) Try adding 2-3 items in project section and now try to delete it make it only 1 project

### What browsers are you seeing the problem on?

Microsoft Edge

### What template are you using?

Onyx

**Comment by dhavalsavalia** [comment]
@AmruthPillai @shivprasad94 I have addressed this in #1779. I hope that helps.

**Comment by brennanmuir** [comment]
@AmruthPillai @dhavalsavalia I'm still not seeing a delete button. Put something in the wrong space and now it's stuck there 
![image](https://github.com/AmruthPillai/Reactive-Resume/assets/18177606/36b7a4f3-5a6d-48a0-89d9-ab7ff3768c00)
![image](https://github.com/AmruthPillai/Reactive-Resume/assets/18177606/3a543454-d3ee-40f9-8035-d2095fd03cc0)

**Comment by dhavalsavalia** [comment]
Oh I am so sorry I missed this @AmruthPillai declined my PR. I will remove option to delete in popup but deleting from the list works fine as I tested.

**Comment by eyalspier** [comment]
I don't have the delete button on my end - I'm running the base self-hosted version via docker compose, and cannot remove e.g. Experience. 
![image](https://github.com/AmruthPillai/Reactive-Resume/assets/26817822/fde153fc-edfc-4153-9e1a-127350f50960)

**Comment by NikoAoi** [comment]
> I don't have the delete button on my end - I'm running the base self-hosted version via docker compose, and cannot remove e.g. Experience. ![image](https://private-user-images.githubusercontent.com/26817822/321920481-fde153fc-edfc-4153-9e1a-127350f50960.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MTM0MDYsIm5iZiI6MTcyMjkxMzEwNiwicGF0aCI6Ii8yNjgxNzgyMi8zMjE5MjA0ODEtZmRlMTUzZmMtZWRmYy00MTUzLTllMWEtMTI3MzUwZjUwOTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAyNTgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNzc3NjE2NjNiYWFjYWUwNzhhMWI4M2Y3NjMwOWU1MTkzOTc4OWRkN2NmYjAzMmZhMDYyY2E0NDUzMjhiMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-GvWwF5JGgv9h6VC6XmGWZQ1HynvUi3VDYqCSvaptO8)

Right-click an item to call the delete menu, if you are calling the browser right-click menu, then the browser plug-in may be causing the error, you can try to right-click in the browser private mode

**Comment by YuWang1222** [comment]
NikoAoi solution worked for me if anyone else is having this issue.
