### ISSUE TITLE
[BUG]  In Downloading resume with DOB (31 December 2003)

### ISSUE THREAD

**Issue by kumarsachinnnn299** [AmruthPillai/Reactive-Resume#929]
**Describe the bug**

**Product Flavor**
- [ ] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser 
 - Version 

**Additional context**

Resume made for DOB 31 December 2003 shows DOB as 30 December 2003 when downloading the resume.
<img width="201" alt="image" src="https://user-images.githubusercontent.com/77502036/175993586-a9a71bae-ead1-4ab2-b823-45dd05a78a63.png"> ---> On site

<img width="175" alt="image" src="https://user-images.githubusercontent.com/77502036/175993690-9e4af93e-2bff-47ec-9bcc-18ce120cf8a2.png"> --> on downloading

**Comment by NR8124** [comment]
I m also facing the same issue

**Comment by 0x346e3730** [comment]
I also have this bug, took a look at the code and don't understand how this is happenning because the download to pdf is chromium loading the resume so I don't see why the date would be different only for the pdf

**Comment by linberson** [comment]
Duplicate https://github.com/AmruthPillai/Reactive-Resume/issues/882

**Comment by realitymolder** [comment]
@0x346e3730  I would assume it's only in the export process minus 1 of a variable, as it happens in the month-only view as well. March become Feb and so on...

**Comment by AmruthPillai** [comment]
This should be fixed as of v3.5.0 :)

**Comment by 0x346e3730** [comment]
@AmruthPillai Can you link the commit that fixes it ? I'm curious what was causing the bug as I thought it would have been a quick PR to fix but couldn't manage to find the cause

**Comment by kumarsachinnnn299** [comment]
The issue is still there and now it is reducing each and every date by 1
