### ISSUE TITLE
[BUG] Google login is broken (Similar to #926)

### ISSUE THREAD

**Issue by JPDucky** [AmruthPillai/Reactive-Resume#935]
**Describe the bug**
Clicking Google login does nothing except the button animation of being clicked

**Product Flavor**
- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Go to 'rxresu.me and click on login'
2. Click on 'Google login'
3. See "login" button being clicked
4. Nothing happens

**Expected behavior**

1. Go to 'rxresu.me and click on login'
2. Click on 'Google login'
3. Be logged in and presented with resume selection page

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 -      fedora 36
 - Browser 
 -      firefox 102.0
 
**Additional context**

This renders the app completely broken as without having access to the app I cannot USE the app.

**Comment by kameshkotwani** [comment]
The same goes for me in Linux Mint. Firefox as well as Brave.

**Comment by kameshkotwani** [comment]
The login is working now.

**Comment by Sporeo** [comment]
not for me, still not working at this current time.

**Comment by kameshkotwani** [comment]
If you're using ad blocker try disabling that.

**Comment by 730730** [comment]
Same here, doesn't work on Firefox nor Chrome on Windows, no adblocker enabled, tried on incognito windows too. Doesn't work on Android Firefox either.

**Comment by AmruthPillai** [comment]
This is due to me having migrated to the new Google Identity Services API.

Apparently, in predictable Google fashion, they are discontinuing the Sign-In API (https://developers.google.com/identity/sign-in/web) that has worked well for so long, thus also breaking a lot of the plugins built around it. So I went ahead and implemented the new API (https://developers.google.com/identity/gsi/web) but it seems to be causing more problems than intended.

The problem is, I have tried replicating the same on my laptop (on all 3 major browsers) and I didn't have any issues. Will keep trying to recreate the issue or getting some sort of logs which can help me pinpoint where things are going wrong.

**Comment by 730730** [comment]
Works on Chrome when logged into the browser itself with my Google account.

**Comment by AmruthPillai** [comment]
Fixed in [v3.6.0](https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v3.6.0)

**Comment by JPDucky** [comment]
This is still not working, ![Screenshot_20220822-134552_Firefox Nightly.jpg](https://user-images.githubusercontent.com/34105363/185995920-1dbcc223-faea-4e01-abba-45be65b30c1b.jpg)

Firefox and Firefox nightly, Android

**Comment by AmruthPillai** [comment]
It looks like you're using an older version (looking at the Google button). Could you please verify whether you are indeed on v3.6.0?
